### ISSUE TITLE
Is there an option to use GPU for the LLM, the inference speed is a little too slow. My GPU utilization is almost zero.

### ISSUE THREAD

**Issue by doubleplusplus** [monarch-initiative/ontogpt#267]
on local model

**Comment by caufieldjh** [comment]
Hi @doubleplusplus,
It looks like the `gpt4all` package doesn't yet support native inference on GPUs (see https://docs.gpt4all.io/gpt4all_faq.html).
We're looking into some alternatives to support GPUs, because you're right - it's pretty slow to run these models on CPU only!

**Comment by TribeDH** [comment]
Hi everyone! Is there any advancement on this? I found out that gpt4all has received support from Vulkan (https://blog.nomic.ai/posts/gpt4all-gpu-inference-with-vulkan) but I have limited knowledge about GPU, so I didn't figure out if it can be integrated in OntoGPT.

**Comment by durabledata** [comment]
You can do this with a little work. You have to change the llm plugin a little and make sure you have Vulkan dependencies installed.

For me with an Nvidia GPU on Ubuntu: `apt-get install -y vulkan-tools libvulkan1 libnvidia-gl-535`

```
find /root/.cache/pypoetry/virtualenvs -type f -name "llm_gpt4all.py" -print0 | xargs -0 sed -i "s/gpt_model = GPT4All(self.filename())/gpt_model = GPT4All(self.filename(), device='gpu')/"
```

**Comment by durabledata** [comment]
llm_gpt4all.py run with ontogpt might try to request the GPU when its already in use and your job will error out. Locking needs to be added.

**Comment by naveenvemulapalli** [comment]
sorry, but why would we want to use Vulkan for nvidia GPUs when there is a more powerful native CUDA support is available from Nvidia? :-) what could be more useful is support for intel iGPU and dGPUs as this will cover rest of us having intel CPUs with onboard/iGPU graphics. We can see llama.cpp project already supports intel iGPUs in couple of ways - using CYCL and Vulkan, though Vulkan would be much worse than even CPU for older Intel iGPUs (such as those below 11th Gen). I tried all of those options presented by llama.cpp project and I can see this - If you have intel iGPUs that are below 11th Gen, there is no real use of running the inference on those GPUs as it would be much slower than running on CPU alone. This happens to be due to the Execution Units (EUs) present in those iGPUs and the fact that they share same system RAM as of CPU. We can see some benefits starting from Intel Iris XE and onwards.

**Comment by caufieldjh** [comment]
This is now supported by #373 and `ollama` - I've found the Docker ollama more reliably works with GPUs, but you may find it works out of the box.
