### ISSUE TITLE
NCIT Mapping error

### ISSUE THREAD

**Issue by pbuendia** [monarch-initiative/ontogpt#414]
Could you please help me with this custom template and explain why these mapping errors occurred and suggest error corrections for the attached mapping file? I am trying to understand what is missing or wrong with the template and have consulted the documentation and issues but cannot figure it out.

1. Why did it not map to [“Human”](https://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C14225) in NCIT: with ID C14225 ?
2. Why did it find http://edamontology.org/data_0006 for Orofacial clefts which is just the root of data?
3. Why are these warnings generated that start with "WARNING:root:Could not find any mappings for..." Example: WARNING:root:Could not find any mappings for http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C16629 ? What part of the template triggers them?

I have attached my template, fairlyz_study.yaml   , the example file, the output file example.output.fairlyz.yml generated by command:
[example.txt](https://github.com/user-attachments/files/16380511/example.txt)
[warnings.txt](https://github.com/user-attachments/files/16380512/warnings.txt)

ontogpt extract -t fairlyz_study.yaml  -i example.txt  --output example.output.fairlyz.yml

[example.output.fairlyz.yml.txt](https://github.com/user-attachments/files/16380705/example.output.fairlyz.yml.txt)
[example.txt](https://github.com/user-attachments/files/16380706/example.txt)
[fairlyz_study.yaml.txt](https://github.com/user-attachments/files/16380707/fairlyz_study.yaml.txt)

**Comment by caufieldjh** [comment]
Hi @pbuendia (I responded by email too, but will provide some more detail here)

> Why did it not map to “Human” in NCIT: with ID C14225 ?

The Bioportal version of NCIT is a bit inconsistent about the prefixes it uses. Try sqlite:obo:ncit as the annotator instead of bioportal:ncit. The specific issue is that the Bioportal version uses `Thesaurus:` as its prefix, while `NCIT` is what the OBO version uses. So the result is that the LLM still identifies "Humans" as an appropriate value for your StudySystemModel class, and tries to ground it against NCIT, but can't find a matching term with the `NCIT:` prefix. 

> Why did it find http://edamontology.org/data_0006 for Orofacial clefts which is just the root of data??

Not sure, but I am guessing that it's because it's trying to ground "Secondary findings in genomic data, Orofacial clefts". The combined phrase happens because the LLM needs to be instructed on how to delimit multiple results. If the "studyfocuses" slot includes material in its description like "provide a semicolon-delimited list of each entity" then the different concepts are more likely to be parsed correctly.

For a very broad category like this, if you don't want to split it into subclasses, it may also help to provide more examples (in the prompt.example field), especially examples matching terms from the annotators.

> What do the attached warnings mean and how can I improve the template so I do not get all the warnings?

Those mapping errors can usually be safely ignored as they mean OntoGPT found an identifier it couldn't map to any other namespace. I should probably make this something other than an error. You may find that these errors stop appearing if you use `sqlite:obo:ncit` instead of `bioportal:ncit` as well.
