### ISSUE TITLE
Support additional chat LLMs

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#70]
GPT-3+ isn't the only LLM out there, and not even the only LLM set up with a chat interface. Let's support others to expand the scope of use cases and offer more flexibility in approaches. More open options would also give us and other OntoGPT users a better idea about the training data used with these models.
This is more of a parent issue - please split as needed.
Candidate LLMs and their accessibility (where known):
* **Bard** - API access is currently waitlisted (Google calls it the PaLM API) and may require using Google Cloud Platform. [See this post](https://www.googlecloudcommunity.com/gc/AI-ML/Google-Bard-API/m-p/538517).
* **Open-Assistant** - https://github.com/LAION-AI/Open-Assistant
* **Alpaca-7B+** - https://github.com/basetenlabs/alpaca-7b-truss
* **StableLM** - https://github.com/stability-AI/stableLM/
* **OpenChatKit** - https://github.com/togethercomputer/OpenChatKit
* **instruct-gpt-j** https://huggingface.co/nlpcloud/instruct-gpt-j-fp16

**Comment by yy20716** [comment]
* I fully support the direction we are heading in, and I am intrigued to see which option we will choose from the several that Harry has proposed.
* I would like to provide some background idea why I support this direction. Currently, I cannot use ontoGPT in my organization as it is due to security concerns around external APIs like OpenAI's. To address this issue, I suggest exploring the possibility of using open-source, local LLMs and their APIs as an alternative to OpenAI's API. This alternative could benefit other users who want to minimize operating costs and speed up processing using their local GPU machines, I believe. Btw, this is not an urgent requirement at all. I just wish to share my mere suggestions. Thanks (CC: @cmungall).

**Comment by yy20716** [comment]
Just FYI. I actually check with my peers about the use of any open-source LLMs in my organization and they suggested the use of instruction-finetuned LLMs: [Flan-T5](https://huggingface.co/docs/transformers/model_doc/flan-t5) and [Dolly v2](https://huggingface.co/databricks/dolly-v2-3b). I wonder if ontoGPT could also additionally suppose these LLMs in the future, if you are okay. Thanks.

**Comment by caufieldjh** [comment]
Needs #93

**Comment by caufieldjh** [comment]
Notes for later reference:
* FLAN-T5: it's on Huggingface Hub , so that's probably the best way to use it through langchain. See https://colab.research.google.com/drive/19Zr9PBgPX3Q8B8yHXYFatCodnNdqP8fg for example
* Dolly-v2: same deal re Huggingface; see potentially outdated example here: https://github.com/hwchase17/langchain/issues/2928

Supporting HF Hub opens up access to many models...

**Comment by remerjohnson** [comment]
> Currently, I cannot use ontoGPT in my organization as it is due to security concerns around external APIs like OpenAI's. To address this issue, I suggest exploring the possibility of using open-source, local LLMs and their APIs as an alternative to OpenAI's API.

I have a similar use case, however, could it ever be abstracted even further, with an option to use _in-house_ LLM services? We are currently working on such a ChatGPT alternative, and it would be amazing to simply plug in that API for ontoGPT...

**Comment by caufieldjh** [comment]
Sure! I'm going to open up another issue along those lines.

**Comment by caufieldjh** [comment]
Supported by #373 now
